

module.exports={
    entry:'./main.js',
    output:{
        path:__dirname+'/dist',
        filename:'build.js',
        publicPath:'dist/'
    },
    mode:'production',
    module:{
        rules:[
            {
                test:/\.css$/,
                loader:'style-loader!css-loader'
            },
            {
                test:/\.scss$/,
                loader:'style-loader!css-loader!sass-loader'
            },
            {
                test:/\.less$/,
                loader:'style-loader!css-loader!less-loader'
            },
            {
                test:/\.(jpg|gif|png)$/,
                loader:'url-loader?limit=30000'
            }
        ]
    }
}